#!/bin/bash
#  arguments <email>

if [ -z $1 ]
then
  echo "Arguments <email>"
  echo ""
  echo "You must supply an email address to build this drupal install."
  exit
fi

# add drush, drupal's command line tool
composer global require drush/drush:dev-master
echo 'export PATH=$HOME/.composer/vendor/bin:$PATH' >> $HOME/.bashrc
PS1='$ ' # running interactively, skip bashrc exit
source $HOME/.bashrc

# config git aliases
git config --global alias.co checkout; 
git config --global alias.br branch; 
git config --global alias.ci commit; 
git config --global alias.st status;

# install and start MySQL
mysql-ctl install
mysql-ctl start
mysql-ctl status

# Use a drush makefile
cd $HOME/workspace
drush make $HOME/workspace/tutorial/drupal7.drush.make -y
git co .gitignore

drush si --db-url=mysqli://$C9_USER@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-name=OOP\ PHP\ Workshop --site-mail=$1 -y

# Ctools & Views & proper toolbar.
drush en admin_menu -y
drush en admin_menu_toolbar -y
drush dis toolbar -y
drush en module_filter -y
drush en fpa -y

drush en ctools -y
drush en views -y
drush en views_ui -y
#drush en advanced_help -y
drush en environment_indicator -y
drush dis overlay -y

#devel stuff
drush en devel -y
drush en devel_generate -y

#migrate
drush en migrate -y
drush en migrate_ui -y

drush en jquery_update -y
drush vset file_temporary_path "/tmp"
drush vset date_default_timezone "America/New_York"
drush vset site_default_country "US"

echo '$base_url = "https://" . getenv("C9_HOSTNAME");' | sudo tee -a $HOME/workspace/sites/default/settings.php

drush cc all

echo ""
echo "-------------"
echo ""
echo "Finished"
echo ""
echo "created Drupal 7 site. Username/passwd admin/admin."
echo ""
echo ""