#!/bin/bash
#  arguments <email>

if [ -z $1 ]
then
  echo "Arguments<email>"
  echo ""
  echo "You must supply an email address to build this drupal install."
  exit
fi

# add drush, drupal's command line tool
composer global require drush/drush:dev-master
echo 'export PATH=$HOME/.composer/vendor/bin:$PATH' >> $HOME/.bashrc
source $HOME/.bashrc

# config git aliases
git config --global alias.co checkout; 
git config --global alias.br branch; 
git config --global alias.ci commit; 
git config --global alias.st status;
