#!/bin/bash

# add drush, drupal's command line tool
composer global require drush/drush:dev-master

# config git aliases
git config --global alias.co checkout; 
git config --global alias.br branch; 
git config --global alias.ci commit; 
git config --global alias.st status;
